apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270adamservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270adamservice
  template:
    metadata:
      name: cit270adamservice
      labels:
        app: cit270adamservice
    spec:
      containers:
      - name: cit270adamservice
        image: gcr.io/mythic-producer-379820/adam-api
        volumeMounts:
        - name: ssl
          mountPath: "/etc/letsencrypt/live/adamowsley.cit270.com/"
        command: ["npm"]
        args: ["run","start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: adamcerts

---
apiVersion: v1
kind: Service
metadata:
  name: stedi-adam-nodeport
spec:
  selector:
    app: cit270adamservice
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-adam-certificate
spec:
  domains:
    - adamowsley.cit270.com

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-adam-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cit270adam
    networking.gke.io/managed-certificates: stedi-adam-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-adam-nodeport
            port:
              number: 80

#---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cit270adamservice-loadbalancer
# spec:
#   selector:
#     app: cit270adamservice
#   type: LoadBalancer
#   ports:
#   - port: 443
#     targetPort: 443
