apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270adamservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270adamservice
  template:
    metadata:
    - name: cit270adamservice
      labels:
        app: cit270adamservice
    spec:
      containers:
      - name: cit270adamservice
        image: mythic-producer-379820
        volumeMounts:
        - name: ssl
            mountpath: "/etc/letsencrypt/live/SSL"
        command: ["npm"]
        args: ["run","start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
          imagePullPolicy: Always
        volumes:
        - name: ssl
          secret:
            secretName: adamcerts
